package com.murat.iftarvakti;

/**
 * Created by murat on 15.04.2017.
 */

public class Constr {

    public String dbToString(String sehir) {

        switch (sehir) {

            case "android_metadata":
                return "";
            case "adana":
                return "ADANA";
            case "Adiyaman":
                return "ADIYAMAN";
            case "Afyonkarahisar":
                return "AFYONKARAHİSAR";
            case "Agri":
                return "AĞRI";
            case "Aksaray":
                return "AKSARAY";
            case "Amasya":
                return "AMASYA";
            case "Ankara":
                return "ANKARA";
            case "Antalya":
                return "ANTALYA";
            case "Ardahan":
                return "ARDAHAN";
            case "Artvin":
                return "ARTVİN";
            case "Aydin":
                return "AYDIN";
            case "Balikesir":
                return "BALIKESİR";
            case "Bartin":
                return "BARTIN";
            case "Batman":
                return "BATMAN";
            case "Bayburt":
                return "BAYBURT";
            case "Bilecik":
                return "BİLECİK";
            case "Bingol":
                return "BİNGÖL";
            case "Bitlis":
                return "BİTLİS";
            case "Bolu":
                return "BOLU";
            case "Burdur":
                return "BURDUR";
            case "Bursa":
                return "BURSA";
            case "Canakkale":
                return "ÇANAKKALE";
            case "Cankiri":
                return "ÇANKIRI";
            case "Corum":
                return "ÇORUM";
            case "Denizli":
                return "DENİZLİ";
            case "Diyarbakir":
                return "DİYARBAKIR";
            case "Duzce":
                return "DÜZCE";
            case "Edirne":
                return "EDİRNE";
            case "Elazig":
                return "ELAZIĞ";
            case "Erzincan":
                return "ERZİNCAN";
            case "Erzurum":
                return "ERZURUM";
            case "Eskisehir":
                return "ESKİŞEHİR";
            case "Gaziantep":
                return "GAZİANTEP";
            case "Giresun":
                return "GİRESUN";
            case "Gumushane":
                return "GÜMÜŞHANE";
            case "Hakkari":
                return "HAKKARİ";
            case "Hatay":
                return "HATAY";
            case "Igdir":
                return "IĞDIR";
            case "Isparta":
                return "ISPARTA";
            case "Istanbul":
                return "İSTANBUL";
            case "Izmir":
                return "İZMİR";
            case "Kahramanmaras":
                return "KAHRAMANMARAŞ";
            case "Karabuk":
                return "KARABÜK";
            case "Karaman":
                return "KARAMAN";
            case "Kars":
                return "KARS";
            case "Kastamonu":
                return "KASTAMONU";
            case "Kayseri":
                return "KAYSERİ";
            case "Kilis":
                return "KİLİS";
            case "Kirikkale":
                return "KIRIKKALE";
            case "Kirklareli":
                return "KIRKLARELİ";
            case "Kirsehir":
                return "KIRŞEHİR";
            case "Kocaeli":
                return "KOCAELİ";
            case "Konya":
                return "KONYA";
            case "Kutahya":
                return "KÜTAHYA";
            case "Malatya":
                return "MALATYA";
            case "Mardin":
                return "MARDİN";
            case "Manisa":
                return "MANİSA";
            case "Mersin":
                return "MERSİN";
            case "Mugla":
                return "MUĞLA";
            case "Mus":
                return "MUŞ";
            case "Nevsehir":
                return "NEVŞEHİR";
            case "Nigde":
                return "NİĞDE";
            case "Ordu":
                return "ORDU";
            case "Osmaniye":
                return "OSMANİYE";
            case "Rize":
                return "RİZE";
            case "Sakarya":
                return "SAKARYA";
            case "Samsun":
                return "SAMSUN";
            case "Sanliurfa":
                return "ŞANLIURFA";
            case "Siirt":
                return "SİİRT";
            case "Sinop":
                return "SİNOP";
            case "Sirnak":
                return "ŞIRNAK";
            case "Sivas":
                return "SİVAS";
            case "Tekirdag":
                return "TEKİRDAĞ";
            case "Tokat":
                return "TOKAT";
            case "Trabzon":
                return "TRABZON";
            case "Tunceli":
                return "TUNCELİ";
            case "Usak":
                return "UŞAK";
            case "Van":
                return "VAN";
            case "Yalova":
                return "YALOVA";
            case "Yozgat":
                return "YOZGAT";
            case "Zonguldak":
                return "ZONGULDAK";
            case "x":
                return "Zonguldak";
        }
        return sehir;
    }

    public String stringToDb(String sehir) {

        switch (sehir) {
            case "ADANA":
                return "adana";
            case "ADIYAMAN":
                return "Adiyaman";
            case "AFYONKARAHİSAR":
                return "Afyonkarahisar";
            case "AĞRI":
                return "Agri";
            case "AKSARAY":
                return "Aksaray";
            case "AMASYA":
                return "Amasya";
            case "ANKARA":
                return "Ankara";
            case "ANTALYA":
                return "Antalya";
            case "ARDAHAN":
                return "Ardahan";
            case "ARTVİN":
                return "Artvin";
            case "AYDIN":
                return "Aydin";
            case "BALIKESİR":
                return "Balikesir";
            case "BARTIN":
                return "Bartin";
            case "BATMAN":
                return "Batman";
            case "BAYBURT":
                return "Bayburt";
            case "BİLECİK":
                return "Bilecik";
            case "BİNGÖL":
                return "Bingol";
            case "BİTLİS":
                return "Bitlis";
            case "BOLU":
                return "Bolu";
            case "BURDUR":
                return "Burdur";
            case "BURSA":
                return "Bursa";
            case "ÇANAKKALE":
                return "Canakkale";
            case "ÇANKIRI":
                return "Cankiri";
            case "ÇORUM":
                return "Corum";
            case "DENİZLİ":
                return "Denizli";
            case "DİYARBAKIR":
                return "Diyarbakir";
            case "DÜZCE":
                return "Duzce";
            case "EDİRNE":
                return "Edirne";
            case "ELAZIĞ":
                return "Elazig";
            case "ERZİNCAN":
                return "Erzincan";
            case "ERZURUM":
                return "Erzurum";
            case "ESKİŞEHİR":
                return "Eskisehir";
            case "GAZİANTEP":
                return "Gaziantep";
            case "GİRESUN":
                return "Giresun";
            case "GÜMÜŞHANE":
                return "Gumushane";
            case "HAKKARİ":
                return "Hakkari";
            case "HATAY":
                return "Hatay";
            case "IĞDIR":
                return "Igdir";
            case "ISPARTA":
                return "Isparta";
            case "İSTANBUL":
                return "Istanbul";
            case "İZMİR":
                return "Izmir";
            case "KAHRAMANMARAŞ":
                return "Kahramanmaras";
            case "KARABÜK":
                return "Karabuk";
            case "KARAMAN":
                return "Karaman";
            case "KARS":
                return "Kars";
            case "KASTAMONU":
                return "Kastamonu";
            case "KAYSERİ":
                return "Kayseri";
            case "KİLİS":
                return "Kilis";
            case "KIRIKKALE":
                return "Kirikkale";
            case "KIRKLARELİ":
                return "Kirklareli";
            case "KIRŞEHİR":
                return "Kirsehir";
            case "KOCAELİ":
                return "Kocaeli";
            case "KONYA":
                return "Konya";
            case "KÜTAHYA":
                return "Kutahya";
            case "MALATYA":
                return "Malatya";
            case "MARDİN":
                return "Mardin";
            case "MANİSA":
                return "Manisa";
            case "MERSİN":
                return "Mersin";
            case "MUĞLA":
                return "Mugla";
            case "MUŞ":
                return "Mus";
            case "NEVŞEHİR":
                return "Nevsehir";
            case "NİĞDE":
                return "Nigde";
            case "ORDU":
                return "Ordu";
            case "OSMANİYE":
                return "Osmaniye";
            case "RİZE":
                return "Rize";
            case "SAKARYA":
                return "Sakarya";
            case "SAMSUN":
                return "Samsun";
            case "ŞANLIURFA":
                return "Sanliurfa";
            case "SİİRT":
                return "Siirt";
            case "SİNOP":
                return "Sinop";
            case "ŞIRNAK":
                return "Sirnak";
            case "SİVAS":
                return "Sivas";
            case "TEKİRDAĞ":
                return "Tekirdag";
            case "TOKAT":
                return "Tokat";
            case "TRABZON":
                return "Trabzon";
            case "TUNCELİ":
                return "Tunceli";
            case "UŞAK":
                return "Usak";
            case "VAN":
                return "Van";
            case "YALOVA":
                return "Yalova";
            case "YOZGAT":
                return "Yozgat";
            case "ZONGULDAK":
                return "Zonguldak";

        }
        return sehir;
    }
}
